### ISSUE TITLE
trailing_zeros fails for Vec type

### ISSUE THREAD

**Issue by yihozhang** [eschnett/SIMD.jl#74] opened 2020-09-13 09:10 UTC
On my computer (Intel i5-7200U, Windows 10, Julia 1.4.2), the following code errors out:
```julia
using SIMD
function test()
    v = Vec{2,UInt64}((1,2))
    trailing_zeros(v)
end

test()
```

When run, it makes JuliaPro crash with the following error message:
```
Please submit a bug report with steps to reproduce this fault, and any error messages that follow (in their entirety). Thanks.
Exception: EXCEPTION_ACCESS_VIOLATION at 0x2f58cd6 -- _ZN4llvm12InstCombiner13visitCallSiteENS_8CallSiteE at C:\Users\zyh38\AppData\Local\JuliaPro-1.4.2-1\Julia-1.4.2\bin\LLVM.dll (unknown line)
in expression starting at C:\Users\zyh38\Documents\academics\genetic-counterfactual\src\Utils\test.jl:7
_ZN4llvm12InstCombiner13visitCallSiteENS_8CallSiteE at C:\Users\zyh38\AppData\Local\JuliaPro-1.4.2-1\Julia-1.4.2\bin\LLVM.dll (unknown line)
_ZN4llvm12InstCombiner13visitCallInstERNS_8CallInstE at C:\Users\zyh38\AppData\Local\JuliaPro-1.4.2-1\Julia-1.4.2\bin\LLVM.dll (unknown line)
_ZN4llvm12InstCombiner3runEv at C:\Users\zyh38\AppData\Local\JuliaPro-1.4.2-1\Julia-1.4.2\bin\LLVM.dll (unknown line)
_ZL31combineInstructionsOverFunctionRN4llvm8FunctionERNS_19InstCombineWorklistEPNS_9AAResultsERNS_15AssumptionCacheERNS_17TargetLibraryInfoERNS_13DominatorTreeERNS_25OptimizationRemarkEmitterEbPNS_8LoopInfoE at C:\Users\zyh38\AppData\Local\JuliaPro-1.4.2-1\Julia-1.4.2\bin\LLVM.dll (unknown line)
_ZN4llvm24InstructionCombiningPass13runOnFunctionERNS_8FunctionE at C:\Users\zyh38\AppData\Local\JuliaPro-1.4.2-1\Julia-1.4.2\bin\LLVM.dll (unknown line)
_ZN4llvm13FPPassManager13runOnFunctionERNS_8FunctionE at C:\Users\zyh38\AppData\Local\JuliaPro-1.4.2-1\Julia-1.4.2\bin\LLVM.dll (unknown line)
_ZN12_GLOBAL__N_113CGPassManager11runOnModuleERN4llvm6ModuleE at C:\Users\zyh38\AppData\Local\JuliaPro-1.4.2-1\Julia-1.4.2\bin\LLVM.dll (unknown line)
_ZN4llvm6legacy15PassManagerImpl3runERNS_6ModuleE at C:\Users\zyh38\AppData\Local\JuliaPro-1.4.2-1\Julia-1.4.2\bin\LLVM.dll (unknown line)
operator() at /cygdrive/d/buildbot/worker/package_win64/build/src\jitlayers.cpp:356
addModule at /cygdrive/d/buildbot/worker/package_win64/build/usr/include/llvm/ExecutionEngine/Orc\IRCompileLayer.h:84 [inlined]
addModule at /cygdrive/d/buildbot/worker/package_win64/build/src\jitlayers.cpp:485
jl_add_to_ee at /cygdrive/d/buildbot/worker/package_win64/build/src\jitlayers.cpp:747 [inlined]
jl_finalize_function at /cygdrive/d/buildbot/worker/package_win64/build/src\jitlayers.cpp:755
getAddressForFunction at /cygdrive/d/buildbot/worker/package_win64/build/src\codegen.cpp:1414
jl_generate_fptr at /cygdrive/d/buildbot/worker/package_win64/build/src\codegen.cpp:1508
jl_compile_method_internal at /cygdrive/d/buildbot/worker/package_win64/build/src\gf.c:1913
_jl_invoke at /cygdrive/d/buildbot/worker/package_win64/build/src\gf.c:2154 [inlined]
jl_apply_generic at /cygdrive/d/buildbot/worker/package_win64/build/src\gf.c:2323
jl_apply at /cygdrive/d/buildbot/worker/package_win64/build/src\julia.h:1700 [inlined]
do_call at /cygdrive/d/buildbot/worker/package_win64/build/src\interpreter.c:369
eval_value at /cygdrive/d/buildbot/worker/package_win64/build/src\interpreter.c:458
eval_stmt_value at /cygdrive/d/buildbot/worker/package_win64/build/src\interpreter.c:409 [inlined]
eval_body at /cygdrive/d/buildbot/worker/package_win64/build/src\interpreter.c:799
jl_interpret_toplevel_thunk at /cygdrive/d/buildbot/worker/package_win64/build/src\interpreter.c:911
jl_toplevel_eval_flex at /cygdrive/d/buildbot/worker/package_win64/build/src\toplevel.c:819
jl_parse_eval_all at /cygdrive/d/buildbot/worker/package_win64/build/src\ast.c:872
include_string at .\loading.jl:1080
#220 at C:\Users\zyh38\.juliapro\JuliaPro_v1.4.2-1\packages\Atom\9h5Up\src\eval.jl:174
withpath at C:\Users\zyh38\.juliapro\JuliaPro_v1.4.2-1\packages\CodeTools\VsjEq\src\utils.jl:30
withpath at C:\Users\zyh38\.juliapro\JuliaPro_v1.4.2-1\packages\Atom\9h5Up\src\eval.jl:9
#219 at C:\Users\zyh38\.juliapro\JuliaPro_v1.4.2-1\packages\Atom\9h5Up\src\eval.jl:171 [inlined]
with_logstate at .\logging.jl:398
with_logger at .\logging.jl:505 [inlined]
#218 at C:\Users\zyh38\.juliapro\JuliaPro_v1.4.2-1\packages\Atom\9h5Up\src\eval.jl:170 [inlined]
hideprompt at C:\Users\zyh38\.juliapro\JuliaPro_v1.4.2-1\packages\Atom\9h5Up\src\repl.jl:127
macro expansion at C:\Users\zyh38\.juliapro\JuliaPro_v1.4.2-1\packages\Media\ItEPc\src\dynamic.jl:24 [inlined]
evalall at C:\Users\zyh38\.juliapro\JuliaPro_v1.4.2-1\packages\Atom\9h5Up\src\eval.jl:160
jl_apply at /cygdrive/d/buildbot/worker/package_win64/build/src\julia.h:1700 [inlined]
do_apply at /cygdrive/d/buildbot/worker/package_win64/build/src\builtins.c:643
jl_f__apply at /cygdrive/d/buildbot/worker/package_win64/build/src\builtins.c:657 [inlined]
jl_f__apply_latest at /cygdrive/d/buildbot/worker/package_win64/build/src\builtins.c:693
#invokelatest#1 at .\essentials.jl:712
jl_apply at /cygdrive/d/buildbot/worker/package_win64/build/src\julia.h:1700 [inlined]
do_apply at /cygdrive/d/buildbot/worker/package_win64/build/src\builtins.c:643
invokelatest at .\essentials.jl:711
jl_apply at /cygdrive/d/buildbot/worker/package_win64/build/src\julia.h:1700 [inlined]
do_apply at /cygdrive/d/buildbot/worker/package_win64/build/src\builtins.c:643
macro expansion at C:\Users\zyh38\.juliapro\JuliaPro_v1.4.2-1\packages\Atom\9h5Up\src\eval.jl:41 [inlined]
#188 at .\task.jl:358
unknown function (ip: 000000001982B3D3)
jl_apply at /cygdrive/d/buildbot/worker/package_win64/build/src\julia.h:1700 [inlined]
start_task at /cygdrive/d/buildbot/worker/package_win64/build/src\task.c:687
Allocations: 39542527 (Pool: 39534541; Big: 7986); GC: 33
LLVM ERROR: starting new .cfi frame before finishing the previous one
```

The same crash occurs for different Vec size (2, 4) and type (Int64, UInt64). However, when running trailing_zeros in the REPL, it succeeds and produces assembly as follows
```
        .text
; ┌ @ simdvec.jl:153 within `trailing_zeros'
        pushq   %rbp
        movq    %rsp, %rbp
        movq    %rcx, %rax
; │┌ @ LLVM_intrinsics_old.jl:124 within `cttz'
; ││┌ @ LLVM_intrinsics_old.jl:127 within `macro expansion'
        vmovdqa (%rdx), %xmm0
        vpcmpeqd        %xmm1, %xmm1, %xmm1
        vpaddq  %xmm1, %xmm0, %xmm1
        vpandn  %xmm1, %xmm0, %xmm0
        movabsq $429639632, %rcx        # imm = 0x199BC7D0
        vmovdqa (%rcx), %xmm1
        vpand   %xmm1, %xmm0, %xmm2
        movabsq $429639648, %rcx        # imm = 0x199BC7E0
        vmovdqa (%rcx), %xmm3
        vpshufb %xmm2, %xmm3, %xmm2
        vpsrlw  $4, %xmm0, %xmm0
        vpand   %xmm1, %xmm0, %xmm0
        vpshufb %xmm0, %xmm3, %xmm0
        vpaddb  %xmm2, %xmm0, %xmm0
        vpxor   %xmm1, %xmm1, %xmm1
        vpsadbw %xmm1, %xmm0, %xmm0
; │└└
        vmovdqa %xmm0, (%rax)
        popq    %rbp
        retq
        nopl    (%rax)
; └
```

I'm not 100% sure but my guess is this is a problem related to vectorized instructions llvm supports. Please let me know if there's any more information I could provide. Also feel free to let me know where I should report it if this is not a SIMD.jl issue. Thanks!

**Comment by KristofferC** [comment] 2020-09-13 15:04
Try with Julia 1.5.

**Comment by yihozhang** [comment] 2020-09-14 04:56
It's still failing for me with Julia 1.5.1. The error message is as follows
```
Please submit a bug report with steps to reproduce this fault, and any error messages that follow (in their entirety). Thanks.
Exception: EXCEPTION_ACCESS_VIOLATION at 0x2ff0779 -- _ZN4llvm12InstCombiner13visitCallBaseERNS_8CallBaseE at C:\Users\zyh38\AppData\Local\JuliaPro-1.5.1-1\Julia-1.5.1\bin\LLVM.dll 
(unknown line)
in expression starting at C:\Users\zyh38\Documents\academics\genetic-counterfactual\src\Utils\test.jl:8
_ZN4llvm12InstCombiner13visitCallBaseERNS_8CallBaseE at C:\Users\zyh38\AppData\Local\JuliaPro-1.5.1-1\Julia-1.5.1\bin\LLVM.dll (unknown line)
_ZN4llvm12InstCombiner13visitCallInstERNS_8CallInstE at C:\Users\zyh38\AppData\Local\JuliaPro-1.5.1-1\Julia-1.5.1\bin\LLVM.dll (unknown line)
_ZN4llvm12InstCombiner3runEv at C:\Users\zyh38\AppData\Local\JuliaPro-1.5.1-1\Julia-1.5.1\bin\LLVM.dll (unknown line)
_ZL31combineInstructionsOverFunctionRN4llvm8FunctionERNS_19InstCombineWorklistEPNS_9AAResultsERNS_15AssumptionCacheERNS_17TargetLibraryInfoERNS_13DominatorTreeERNS_25OptimizationRemarkEmitterEPNS_18BlockFrequencyInfoEPNS_18ProfileSummaryInfoEbPNS_8LoopInfoE at C:\Users\zyh38\AppData\Local\JuliaPro-1.5.1-1\Julia-1.5.1\bin\LLVM.dll (unknown line)
_ZN4llvm24InstructionCombiningPass13runOnFunctionERNS_8FunctionE at C:\Users\zyh38\AppData\Local\JuliaPro-1.5.1-1\Julia-1.5.1\bin\LLVM.dll (unknown line)
_ZN4llvm13FPPassManager13runOnFunctionERNS_8FunctionE at C:\Users\zyh38\AppData\Local\JuliaPro-1.5.1-1\Julia-1.5.1\bin\LLVM.dll (unknown line)
_ZN12_GLOBAL__N_113CGPassManager11runOnModuleERN4llvm6ModuleE at C:\Users\zyh38\AppData\Local\JuliaPro-1.5.1-1\Julia-1.5.1\bin\LLVM.dll (unknown line)
_ZN4llvm6legacy15PassManagerImpl3runERNS_6ModuleE at C:\Users\zyh38\AppData\Local\JuliaPro-1.5.1-1\Julia-1.5.1\bin\LLVM.dll (unknown line)
operator() at /cygdrive/d/buildbot/worker/package_win64/build/src\jitlayers.cpp:520
addModule at /cygdrive/d/buildbot/worker/package_win64/build/usr/include/llvm/ExecutionEngine/Orc\IRCompileLayer.h:93 [inlined]
addModule at /cygdrive/d/buildbot/worker/package_win64/build/src\jitlayers.cpp:648
jl_add_to_ee at /cygdrive/d/buildbot/worker/package_win64/build/src\jitlayers.cpp:893
jl_add_to_ee at /cygdrive/d/buildbot/worker/package_win64/build/src\jitlayers.cpp:955
jl_add_to_ee at /cygdrive/d/buildbot/worker/package_win64/build/src\jitlayers.cpp:977 [inlined]
_jl_compile_codeinst at /cygdrive/d/buildbot/worker/package_win64/build/src\jitlayers.cpp:126
jl_generate_fptr at /cygdrive/d/buildbot/worker/package_win64/build/src\jitlayers.cpp:302
jl_compile_method_internal at /cygdrive/d/buildbot/worker/package_win64/build/src\gf.c:1964
jl_compile_method_internal at /cygdrive/d/buildbot/worker/package_win64/build/src\gf.c:1931 [inlined]
_jl_invoke at /cygdrive/d/buildbot/worker/package_win64/build/src\gf.c:2224 [inlined]
jl_apply_generic at /cygdrive/d/buildbot/worker/package_win64/build/src\gf.c:2398
jl_apply at /cygdrive/d/buildbot/worker/package_win64/build/src\julia.h:1690 [inlined]
do_call at /cygdrive/d/buildbot/worker/package_win64/build/src\interpreter.c:117
eval_value at /cygdrive/d/buildbot/worker/package_win64/build/src\interpreter.c:206
eval_stmt_value at /cygdrive/d/buildbot/worker/package_win64/build/src\interpreter.c:157 [inlined]
eval_body at /cygdrive/d/buildbot/worker/package_win64/build/src\interpreter.c:548
jl_interpret_toplevel_thunk at /cygdrive/d/buildbot/worker/package_win64/build/src\interpreter.c:660
jl_toplevel_eval_flex at /cygdrive/d/buildbot/worker/package_win64/build/src\toplevel.c:840
jl_parse_eval_all at /cygdrive/d/buildbot/worker/package_win64/build/src\ast.c:913
jl_load_file_string at /cygdrive/d/buildbot/worker/package_win64/build/src\ast.c:953
include_string at .\loading.jl:1088
include_string at .\loading.jl:1096 [inlined]
include_string at C:\Users\zyh38\.julia\packages\CodeTools\VsjEq\src\eval.jl:30
unknown function (ip: 0000000025B90659)
#202 at C:\Users\zyh38\.julia\packages\Atom\ZeFbA\src\eval.jl:119
withpath at C:\Users\zyh38\.julia\packages\CodeTools\VsjEq\src\utils.jl:30
unknown function (ip: 0000000025B90524)
withpath at C:\Users\zyh38\.julia\packages\Atom\ZeFbA\src\eval.jl:9
#201 at C:\Users\zyh38\.julia\packages\Atom\ZeFbA\src\eval.jl:118
unknown function (ip: 0000000025B8FD53)
with_logstate at .\logging.jl:408
with_logger at .\logging.jl:514 [inlined]
#200 at C:\Users\zyh38\.julia\packages\Atom\ZeFbA\src\eval.jl:117 [inlined]
hideprompt at C:\Users\zyh38\.julia\packages\Atom\ZeFbA\src\repl.jl:127
macro expansion at C:\Users\zyh38\.julia\packages\Atom\ZeFbA\src\eval.jl:116 [inlined]
macro expansion at C:\Users\zyh38\.julia\packages\Media\ItEPc\src\dynamic.jl:24 [inlined]
eval at C:\Users\zyh38\.julia\packages\Atom\ZeFbA\src\eval.jl:113
unknown function (ip: 0000000025BB5603)
jl_apply at /cygdrive/d/buildbot/worker/package_win64/build/src\julia.h:1690 [inlined]
do_apply at /cygdrive/d/buildbot/worker/package_win64/build/src\builtins.c:655
jl_f__apply at /cygdrive/d/buildbot/worker/package_win64/build/src\builtins.c:669 [inlined]
jl_f__apply_latest at /cygdrive/d/buildbot/worker/package_win64/build/src\builtins.c:705
#invokelatest#1 at .\essentials.jl:710
jl_apply at /cygdrive/d/buildbot/worker/package_win64/build/src\julia.h:1690 [inlined]
do_apply at /cygdrive/d/buildbot/worker/package_win64/build/src\builtins.c:655
invokelatest at .\essentials.jl:709
jl_apply at /cygdrive/d/buildbot/worker/package_win64/build/src\julia.h:1690 [inlined]
do_apply at /cygdrive/d/buildbot/worker/package_win64/build/src\builtins.c:655
macro expansion at C:\Users\zyh38\.julia\packages\Atom\ZeFbA\src\eval.jl:41 [inlined]
#184 at .\task.jl:356
unknown function (ip: 0000000019EEF363)
jl_apply at /cygdrive/d/buildbot/worker/package_win64/build/src\julia.h:1690 [inlined]
start_task at /cygdrive/d/buildbot/worker/package_win64/build/src\task.c:707
Allocations: 62162857 (Pool: 62142269; Big: 20588); GC: 63

atexit hook threw an error: ReadOnlyMemoryError()
```

**Comment by KristofferC** [comment] 2020-09-18 13:35
Finally, try on nightly. It works for me there.

**Comment by yihozhang** [comment] 2020-09-18 22:42
Still not working for me (on the latest master branch). I don't see your commit related to this issue either, how can I find it? Thanks!

**Comment by KristofferC** [comment] 2020-09-19 14:10
```
julia> using SIMD

julia> function test()
           v = Vec{2,UInt64}((1,2))
           trailing_zeros(v)
       end
test (generic function with 1 method)

julia> test()
<2 x UInt64>[0x0000000000000000, 0x0000000000000001]
```

on the mac latest. Maybe something with Windows?

**Comment by yihozhang** [comment] 2020-09-26 10:20
Just had a chance to test it on Mac, still failing:

```julia
julia> Pkg.add("SIMD")
 Installing known registries into `~/.julia`
######################################################################## 100.0%
      Added registry `General` to `~/.julia/registries/General`
  Resolving package versions...
  Installed SIMD ─ v3.1.0
Updating `~/.julia/environments/v1.5/Project.toml`
  [fdea26ae] + SIMD v3.1.0
Updating `~/.julia/environments/v1.5/Manifest.toml`
  [fdea26ae] + SIMD v3.1.0

julia> using SIMD
[ Info: Precompiling SIMD [fdea26ae-647d-5447-a871-4b548cad5224]

julia> function test()
       v=Vec{2,UInt64}((1,2))
       trailing_zeros(v)
       end
test (generic function with 1 method)

julia> test()
[1]    11151 segmentation fault  julia
```

**Comment by KristofferC** [comment] 2020-09-26 11:15
Might be a difference in architecture that causes it then? Can you build with assertions enabled and try?

**Comment by yihozhang** [comment] 2020-09-26 21:16
How can I do this? Thanks

**Comment by jakobnissen** [comment] 2020-11-01 09:58
I can reproduce this.
```
julia> versioninfo()
Julia Version 1.5.0-rc2.0
Commit 7f0ee122d7 (2020-07-27 15:24 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: AMD Ryzen 7 4700U with Radeon Graphics
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-9.0.1 (ORCJIT, znver1)
Environment:
  JULIA_EDITOR = micro
```
For me it segfaults. Even doing `@code_llvm test()` segfaults. It appears to be an LLVM issue. Can I help this issue somehow?

**Comment by KristofferC** [comment] 2020-11-01 13:38
> I can reproduce this.
> Julia Version 1.5.0-rc2.0

Make sure you run with latest version (nightly if possible) because llvm does quite a lot of bugfixing in this area.

> Can I help this issue somehow?

You can build Julia + LLVM with assertions, try to figure out what the problem is, and report it to wherever is suitable (maybe LLVM).

**Comment by jakobnissen** [comment] 2020-11-01 13:40
Just tested it on nightly, you're right, it did work there. Sorry to disturb!

**Comment by KristofferC** [comment] 2021-02-02 07:29
I'm guessing this is fixed now then. I don't think there is a bug in the package so not much that can be done from this end.

**Closed by KristofferC** 2021-02-02 07:29 UTC
